"""Stub file for custom_components/reflex_pdfslick/pdfslick.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
import reflex as rx

PDFSLICK_REACT = "@pdfslick/react@4.0.0"
PDFSLICK_CSS = "@pdfslick/react/dist/pdf_viewer.css"
PDFJS_DIST = "pdfjs-dist@^6.0.227"
_WRAPPER_ASSET = rx.asset("PdfSlickWrapper.tsx", shared=True)

class PdfSlick(rx.NoSSRComponent):
    def add_imports(self) -> dict[str, Any]: ...
    @classmethod
    def create(
        cls,
        *children,
        url: Var[str] | str | None = None,
        scale_value: Var[str] | str | None = None,
        single_page_viewer: Var[bool] | bool | None = None,
        remove_page_borders: Var[bool] | bool | None = None,
        thumbnail_width: Var[int] | int | None = None,
        show_thumbnails: Var[bool] | bool | None = None,
        horizontal_thumbnails: Var[bool] | bool | None = None,
        command: Var[dict[str, Any]] | dict[str, Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_document_load: Optional[EventType[Any]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_error: Optional[EventType[Any]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_metadata: Optional[EventType[Any]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_page_change: Optional[EventType[Any]] = None,
        on_scale_change: Optional[EventType[Any]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "PdfSlick":
        """Create the component.

        Args:
            *children: The children of the component.
            url: --- Props (camelCased to JS automatically) -----------------------------
            scale_value: no description
            single_page_viewer: no description
            remove_page_borders: no description
            thumbnail_width: no description
            show_thumbnails: no description
            horizontal_thumbnails: no description
            command: Declarative imperative-control channel (Phase 3): a command object the wrapper applies then clears. Built with helpers in ``commands.py``.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_document_load: --- Events ------------------------------------------------------------- Each forwards the JS callback's first argument to the Python handler.
            on_page_change: no description
            on_scale_change: no description
            on_error: no description
            on_metadata: no description
            **props: The props of the component.

        Returns:
            The component."""
        ...

pdf_slick = PdfSlick.create
